make all:
	gcc -ggdb -o kss1 kss1.c syscalls.c
	gcc -ggdb -o suclient suclient.c funcionesPayload.c
	gcc -ggdb -o ftpfake ftpfake.c funcionesPayload.c
	gcc -ggdb -o fssfake fssfake.c funcionesPayload.c
	gcc -ggdb -o vdafake vdafake.c funcionesPayload.c